title: Heloisa — AppSec Lead
description: AppSec • DevSecOps • Secure SDLC — EN / FR / BR
theme: jekyll-remote-theme

# Optional polish
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Identify the repo for the github-metadata plugin
repository: hel-isa/hel-isa.github.io
url: https://hel-isa.github.io
domain: hel-isa.github.io
baseurl: /hel-isa/

# Site metadata
author:
  name: Heloisa Reis

# Social (shown by minima if configured)
minima:
  social_links:
    - platform: github
      user_url: https://github.com/hel-isa
    - platform: linkedin
      user_url: https://www.linkedin.com/in/helosilvareis/
